### ISSUE TITLE
IA14

### ISSUE THREAD

**Issue by dilanSachi** [codezilla2018/Todo4U#1]
@isuru117 
can you tell me what is simply meant by the "Things to do can be added with hyperlinks"???

**Comment by isuru117** [comment]
Hi, can you direct me to where that is mentioned?

**Comment by dilanSachi** [comment]
**IA14 : Smart Todo list Firefox extension. Things to do can be added with hyperlinks and will be triggered with reminders and scheduling**

it's in the project idea as above mentioned

**Comment by isuru117** [comment]
It means a Firefox extension (that is somewhat similar to the Google Keep extension for Google Chrome)  where the user can add a simple note with optional functionality to add a reminder(which should be triggered at the time the user schedules it to be triggered) and also optionally, the ability to save the link of the page the user is visiting.

**Comment by dilanSachi** [comment]
i got it. thanks
